### PR TITLE
New flash creation dialog in QML

### PR DESCRIPTION
**Pull request by Vogtinator**
New flash creation dialog + an Android usability improvement + QML fixes.

With this, the warnings on exit are finally gone!

Android             |  Linux (Plasma Wayland)
:-------------------------:|:-------------------------:
 | Screenshot_20220417_202742

@adriweb Please test whether the dialog works as expected on macOS and especially iOS as well.

### CODE REVIEW

**Comment by adriweb** [comment]
I guess it's OK?
image

**Comment by adriweb** [comment]
That saif, the two list selects seem to be read-only somehow:
image

**Comment by Vogtinator** [comment]
Do they only look read-only or are they actually read-only? Might just be a weird color scheme

**Comment by adriweb** [comment]
They're actually read only.
Is there any condition that makes them this way?

**Comment by Vogtinator** [comment]
No, that makes no sense... https://doc.qt.io/qt-5/qml-qtquick-controls-combobox.html doesn't even have an `enabled` property!

Do other comboboxes in the config dialog behave similarly?

**Comment by adriweb** [comment]
> Do other comboboxes in the config dialog behave similarly?

Everything else behaves correctly

**Comment by Vogtinator** [comment]
Can you add this in strategic places to find what disables it?

```
Component.onCompleted: console.log("Enabled", enabled)    
onEnabledChanged: console.log("Enabled changed", enabled)
```

**Comment by adriweb** [comment]
Well, I tried, and it prints this:
```
qml: subtypeCombo Enabled true
qml: modelCombo Enabled true
```

Seems like a Qt bug on macOS then, who knows....

That said, even if the UI is messed up, tabbing to the control to get its focus, then pressing the arrow keys to select the wanted option, works fine (as long as you don't open the dropdown)

**Comment by Vogtinator** [comment]
> OK it is a Qt Bug, but not fixed in OSS releases ... https://bugreports.qt.io/browse/QTBUG-89607 / https://forum.qt.io/topic/123101/quick-controls-1-combobox-items-unselectable-on-macos/9

According to that, the issue is fixed in 5.15.3. Can you try the latest 5.15.5?

**Comment by adriweb** [comment]
> According to that, the issue is fixed in 5.15.3. Can you try the latest 5.15.5?

Well 5.15.5 doesn't seem to be available - it stops at 5.15.2 here... 🤔

**Comment by Vogtinator** [comment]
> > According to that, the issue is fixed in 5.15.3. Can you try the latest 5.15.5?
> 
> Well 5.15.5 doesn't seem to be available - it stops at 5.15.2 here... thinking

Maybe they just do (pathetic) delayed source releleases but no binary ones? Annoying...

**Comment by adriweb** [comment]
Might be time to upgrade to Qt6 :P

**Comment by Vogtinator** [comment]
I added a workaround for the Qt bug, can you try whether that works?

**Comment by adriweb** [comment]
Some usual Qt weirdness regarding text alignment and focus oddities, but it does work :)

image

**Review by adriweb — APPROVED** [review]
The UI now works fine for me

**Comment by Vogtinator** [comment]
Were you able to test on iOS as well?

**Comment by adriweb** [comment]
Ah, no, not yet anyway, just macOS for now.

**Comment by adriweb** [comment]
tested OK on iOS

**Pull request merged**
