### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by Atrate**
**Changes:**
 - Added Polish translation
 - Capitalized "Firebird" where appropriate

Signed-off-by: Atrate <Atrate@protonmail.com>

### CODE REVIEW

**Comment by Vogtinator** [comment]
Thanks! Please run `lrelease i18n/pl_PL.ts` and add `i18n/pl_PL.qm` to `resources.qrc`.

Or if you'd like to do some cleanup, try `CONFIG += lrelease embed_translations` in `firebird.pro`, which might need some adjustments elsewhere.

**Comment by Atrate** [comment]
Done, @Vogtinator

**Comment by Vogtinator** [comment]
Looks like you did both now - with the added `CONFIG` values the `.qm` files can be dropped from the repo and `resources.qrc`.
If that works (you might have to adjust the path in `main.cpp` and `mainwindow.cpp`), you can do that.
Or undo the `CONFIG` change, as otherwise it looks good now.

**Comment by Atrate** [comment]
Alright, it's simpler to just remove the config override. Done.

**Comment by Vogtinator** [comment]
I gave it a quick try and noticed that the dock window titles aren't translated. That's most likely a bug in the code though and not related to this translation, as the other languages are also affected.

Thanks for the contribution!

**Pull request merged**
