### PR TITLE
Update translations for 1.6

### PR DESCRIPTION
**Pull request by Vogtinator**
- [X] de_DE
- [x] fr_FR
- [x] pl_PL

@adriweb Could you handle the fr_FR translation again?

@Atrate Could you handle the pl_PL translation again?

### CODE REVIEW

**Comment by Atrate** [comment]
> * [x]  de_DE
> 
>     * [ ]  fr_FR
> 
>     * [ ]  pl_PL
> 
> 
> @adriweb Could you handle the fr_FR translation again?
> 
> @Atrate Could you handle the pl_PL translation again?

I probably won't have much time until around the middle of December, if I don't forget I can make  PR later

**Comment by Vogtinator** [comment]
> >   * [x]   de_DE
> >   * [x]   fr_FR
> >   * [ ]   pl_PL
> > 
> > @adriweb Could you handle the fr_FR translation again?
> > @Atrate Could you handle the pl_PL translation again?
> 
> I probably won't have much time until around the middle of December, if I don't forget I can make a PR later

Thanks, sounds good!

**Comment by Vogtinator** [comment]
> > @Atrate Could you handle the pl_PL translation again?
>
> I probably won't have much time until around the middle of December, if I don't forget I can make a PR later

Hi! Do you think it makes sense to wait until you're able to submit them or should we release 1.6 without complete pl_PL translations? Now that we have build pipelines set up for everything (except iOS...), we can just get a 1.6.1 out if necessary.

**Comment by Atrate** [comment]
https://github.com/nspire-emus/firebird/commit/c9c5204c066a4ef0ab2050f60d5db7613aeb15b5

Should I make a PR into `translations-1.4`?

**Comment by Vogtinator** [comment]
> Done, @Vogtinator. [c9c5204](https://github.com/nspire-emus/firebird/commit/c9c5204c066a4ef0ab2050f60d5db7613aeb15b5)

Awesome, thanks!

> Should I make a PR into `translations-1.4`?

Yes, please

> (I cloned the translations-1.4 branch and updated all the strings that needed attention in Qt Linguist, I presume that's what was supposed to be done?)

Yep!

**Comment by Atrate** [comment]
> >Should I make a PR into translations-1.4?

> Yes, please

Done

**Pull request merged**
