### PR TITLE
More user- and mobile- friendly configuration

### PR DESCRIPTION
**Pull request by Vogtinator**
It would be great to get this a bit tested, especially against possible regressions.

### CODE REVIEW

**Comment by awinterstale33** [comment]
can I help in anyway? I  don't have much programing experience, so I can't help in that regard but I'm willing to whatever I can to further this project.   I don't know if you remember but I offered you my old Samsung Galaxy Note 2 if that would help.

**Comment by Vogtinator** [comment]
> can I help in anyway? I don't have much programing experience, so I can't help in that regard but I'm willing to whatever I can to further this project.

Yes, I'll provide a build for Android later for testing.

> I don't know if you remember but I offered you my old Samsung Galaxy Note 2 if that would help.

It would help if there is an issue on that device that I'm unable to reproduce.

**Comment by NikBarbour** [comment]
An Android build would be great.

I can test on a Note 4 SM-N910F running LP5.0.1, and a Shield K1 with
MM6.0.1 if it helps

**Comment by Vogtinator** [comment]
Here's a test build for android. Also contains some extra debugging for emulation startup.
Note that this is a debug build, so it'll be much slower than a normal release build.

[QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/587542/QtApp-debug.zip)

The areas that need testing the most:

- Keypad and Touchpad. I changed the behaviour a bit to improve usability on touch screens
- Settings area, like on desktop. Just play around with it a bit, if you don't understand what something does, the UI isn't self-expanatory enough and that needs to be fixed
- HiDPI scaling. Are all texts readable? Some buttons/text input fields do not quite match, that's a known issue
- Migration: Are the values for flash/boot1 and snapshot kept?

**Comment by plusCubed** [comment]
Keypad: 
- Right image is from NSpiroid. I find that one much easier to use because of larger buttons. 
- It also moves up XYZ in the "up" position (it has a toggle to go to the down position with the full keyboard)
- Some symbols are not working in firebird (empty boxes)



Settings:
- Can get stuck between keypad and settings
- Text and buttons are tiny on my Nexus 6P (xxhdpi)
- Wasn't obvious how to configure kit, needed to scroll down



Migration: Works fine.

**Comment by adriweb** [comment]
Built for iOS 10.1 (iPhone 7), same as the post above regarding the kit configuration (at least when it didn't get corrupted and made an empty list :D): the configuration wasn't on screen, had to scroll.
On iOS, there doesn't seem to be any symbol issue. I extremely despise Nspiroid's keypad look, but I can imagine that bigger buttons, especially on smaller devices, can be useful.

Screenshots: https://imgur.com/a/gEbrO

**Comment by Vogtinator** [comment]
> Right image is from NSpiroid. I find that one much easier to use because of larger buttons.

Firebird's button appear smaller but have a simliar sized active area (+10px (96dpi) above and below on the big ones)

> It also moves up XYZ in the "up" position (it has a toggle to go to the down position with the full keyboard)

Doesn't sound that useful to me, actually.

> Some symbols are not working in firebird (empty boxes)
Seems to be the font, some more keys need to use pixmaps.

> Can get stuck between keypad and settings

How?

> Text and buttons are tiny on my Nexus 6P (xxhdpi)

Ok, so I have to implement scaling differently...

> Wasn't obvious how to configure kit, needed to scroll down

With proper scaling that shouldn't happen anymore.

> Migration: Works fine.

Thanks for the helpful feedback!

**Comment by plusCubed** [comment]
> Firebird's button appear smaller but have a simliar sized active area (+10px (96dpi) above and below on the big ones)

Ah, got it. Hmm... I agree firebird looks much nicer, but the layout makes me feel like I have to precisely hit the buttons, even if that's not the case. Maybe it's just me, but I prefer lines to be drawn at the touch target bounds.

>>It also moves up XYZ in the "up" position (it has a toggle to go to the down position with the full keyboard)

>Doesn't sound that useful to me, actually.

Maybe my use case is different - the XYZ buttons are very common for me to use. It's not very convenient to have to scroll down every time, partly because scrolling only works if I start in a blank area. For reference, here are the two layouts for the keypad in Nspiroid - there's a toggle button on the top left of the interface that allows quickly toggling between these two.




>>Can get stuck between keypad and settings

> How?

If I scroll halfway in between the two pages, it doesn't finish moving.

**Comment by bob8490** [comment]
Just to throw it out there - I have a 7.1.2 iPad Air I could test on, as well as a 9.0.2 iPhone 6. Both are jailbroken.

**Comment by adriweb** [comment]
Nice - there will be 32-bit and 64-bit builds (.ipa) for iOS (soon - when this is merged I guess?) so you'll be able to try (if you can't already by compiling yourself).
Then, if need be, we can fix some things before the actual github release update.

**Comment by bob8490** [comment]
Great! I'll keep an eye on it.

I had trouble compiling last time I tried - I forget what the issue was. Maybe I'll give it a shot again if I can find the time.

**Comment by Vogtinator** [comment]
Here is a new build for android which has automatic HiDPI scaling disabled and uses its own calculations now. On my device the debugging configuration page does not quite fit anymore, but I don't consider that as too critical for now as the debugger isn't that useful on mobile platforms anyway...

I also rewrote the way the swiping between the keypad and the controls work, but it needs some major tuning to feel right, so it won't be part of this release.

[QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/601560/QtApp-debug.zip)

**Comment by Vogtinator** [comment]
I'll merge this now, if there are any remaining issues please open a new issue instead of replying here.
Thanks for all the feedback!

**Comment by gchiozzi** [comment]
I have done some basic tests of the Android apk on my Samsung Galaxy S4 Mini and on my Galaxy Notes 10.4 2014.
Seems to work very well: much more usable than the previous release. Seems quite stable and sufficiently responsive.
I am quite happy! Thanks.

A couple of suggestions:
- I think that on the tablet it should be possible to display the complete keyboard keeping the aspect ratio but zooming it out and leaving black bars on the sides. The keys would still be bigger than on the real device and on the S4, where they are still quite usable. Then we would not have to scroll to get to the alpha-keys. 
- What about removing the Start, Reset,Resume,Save buttons and attach them to the android menu button instead? Then you could center the display as well.

Thanks ! Great work!

               Gianluca

**Comment by Vogtinator** [comment]
> I have done some basic tests of the Android apk on my Samsung Galaxy S4 Mini and on my Galaxy Notes 10.4 2014.
> Seems to work very well: much more usable than the previous release. Seems quite stable and sufficiently responsive.
> I am quite happy! Thanks.

Thanks for the feedback!

> A couple of suggestions:
>
> I think that on the tablet it should be possible to display the complete keyboard keeping the aspect ratio but zooming it out and leaving black bars on the sides. The keys would still be bigger than on the real device and on the S4, where they are still quite usable. Then we would not have to scroll to get to the alpha-keys.

As this feature gets requested fairly often, I quickly implemented it, please give it a try:
[QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/607641/QtApp-debug.zip)

> What about removing the Start, Reset,Resume,Save buttons and attach them to the android menu button instead? Then you could center the display as well.

No, as:
* Not easy to implement with Qt Quick
* Often seen as bad design (two steps instead of one)
* There is no menu button on iOS

> Thanks ! Great work!

**Comment by gchiozzi** [comment]
Dear Fabian,

Tested on the Notes 10.4.
In landscape mode is exactly as your screenshot and it works fine.

Unfortunately in portrait mode the keyboard is completely gone: I just get the display in the middle of the screen.

     Thanks,

               Gianluca

**Comment by Vogtinator** [comment]
> Unfortunately in portrait mode the keyboard is completely gone: I just get the display in the middle of the screen.

That is unfortunate indeed... Does it also break if you start the app in portrait mode or only if you switch from landscape into portrait?

**Comment by gchiozzi** [comment]
Also if I start it in in portrait.

**Comment by Vogtinator** [comment]
Ok, that makes debugging easier. Can you upload a screenshot?

**Comment by gchiozzi** [comment]
Here the screenshot.
flashannotate 1

**Comment by Vogtinator** [comment]
Although I could not reproduce the exact behaviour (only happened after resizing), it should be fixed now: 
[QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/609983/QtApp-debug.zip)

**Comment by gchiozzi** [comment]
Now I have again the keyboard on portrait mode.

But the full keyboard is only in landscape mode (both on Samsung Notes 10.1 and S4-Mini.
In portrait mode I have the usual scrolling keyboard on both devices.

Did I misunderstand and you have implemented the full keyboard only in landscape mode?
If it should work also in portrait, could this be related with the resolution?
The Notes 10.1 ha a screen of 2560 x 1600 Pixel and it is 10.1 Inches.

Anyway, in landscape it works very well and I can easily switch between landscape and portrait.
Only regret: I am left handed and I would be happier with the keyboard on the left side rather than on the right side.

Thanks,

                Gianluca

**Comment by Vogtinator** [comment]
>Did I misunderstand and you have implemented the full keyboard only in landscape mode?
> If it should work also in portrait, could this be related with the resolution?

I made it so that the keyboard is visible in landscape mode and the usual layout in portrait mode.
It makes it much easier to be compatible over a wide range of different display dpi and sizes, especially
because some devices flat out lie about those...
IMO the screen space is much more efficiently used in portrait mode that way.

> Only regret: I am left handed and I would be happier with the keyboard on the left side rather than on the right side.

I see, I'll likely implement a switch for that in the settings today.

**Comment by Vogtinator** [comment]
> I see, I'll likely implement a switch for that in the settings today.

And done: [QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/612043/QtApp-debug.zip)

**Pull request merged**
