### PR TITLE
Support native Android file picker used by Qt >= 5.13

### PR DESCRIPTION
**Pull request by Vogtinator**
Like #94, but uses the now native support in Qt 5.13.

Unfortunately it does not support creation of files, so only existing files can be written.

~Needs some testing, here's an APK: [firebird.zip](https://github.com/nspire-emus/firebird/files/3326263/firebird.zip)~

Depends on #184

### CODE REVIEW

**Comment by Vogtinator** [comment]
Added "WIP" to the title as the ugly `FB_NEED_GUI_OPEN` define has to go.

**Comment by Vogtinator** [comment]
Something that also needs to be fixed is sending files, currently it'd try to send as an invalid file name.

**Comment by Vogtinator** [comment]
Rebased on #184, refactored to get rid of `FB_USE_GUI_OPEN`. Dialogs work fine with Qt fix from the 5.14 branch.

Only missing piece is the usblink filename now.

**Comment by Vogtinator** [comment]
Hacked support for those urls into usblink.c as well.

**Comment by Vogtinator** [comment]
Tested on real HW now as well, working fine.

**Comment by Vogtinator** [comment]
Got confirmation that this fixes #144, so this can go in. @adriweb can you verify that it still builds for aarch64 iOS?

**Comment by adriweb** [comment]
Yep, works fine.

**Pull request merged**
